// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }


// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import FileUpload from "@/Compo/FileUpload";
// // import DarkMode from "@/Compo/DarkMode";
// import NavBar from "@/Compo/NavBar";


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "CSV Prediction App",
//   description: "Upload CSV files to get predictions using ML models.",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <head>
//         <script
//           dangerouslySetInnerHTML={{
//     __html: `
//       (function() {
//         try {
//           const theme = localStorage.getItem('theme');
//           if (theme === 'dark') {
//             document.documentElement.classList.add('dark');
//           } else {
//             document.documentElement.classList.remove('dark');
//           }
//         } catch (_) {}
//       })();
//     `,
//   }}
//         />
//       </head>
//       <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}>
//         {/* NavBar */}
//         <NavBar />
//         {/* Main page content */}
//         <div className="flex-grow">{children}</div>

//         {/* Footer */}
//         <footer className="w-full text-center py-4 border-t mt-10 bg-white text-sm text-gray-500">
//           &copy; {new Date().getFullYear()} CreditSense ML App. Built with ❤️ using Next.js and Tailwind CSS.
//         </footer>
//       </body>
//     </html>
//   );
// }


// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import FileUpload from "@/Compo/FileUpload";
// // import DarkMode from "@/Compo/DarkMode";
// import NavBar from "@/Compo/NavBar";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "CSV Prediction App",
//   description: "Upload CSV files to get predictions using ML models.",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en" className="bg-white text-black dark:bg-zinc-900 dark:text-white">
//       <head>
        
//       </head>
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen bg-white text-black dark:bg-zinc-900 dark:text-white`}
//       >
//         {/* NavBar */}
//         <NavBar />

//         {/* Main page content */}
//         <div className="flex-grow">{children}</div>

//         {/* Footer */}
//         <footer className="w-full text-center py-4 border-t mt-10 bg-white dark:bg-zinc-800 text-sm text-gray-500 dark:text-gray-400">
//           &copy; {new Date().getFullYear()} CreditSense ML App. Built with ❤️ using Next.js and Tailwind CSS.
//         </footer>
//       </body>
//     </html>
//   );
// }


import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/Compo/NavBar";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "CSV Prediction App",
  description: "Upload CSV files to get predictions using ML models.",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-white text-black">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen bg-gray-300`}
      >
          <NavBar />
          <div className="flex-grow">{children}</div>

          <footer className="w-full text-center py-4 border-t mt-10 bg-blue-900 text-sm text-white dark:text-gray-400">
            &copy; {new Date().getFullYear()} PayScore
          </footer>
      </body>
    </html>
  );
}
